# Generated by Django 5.0.6 on 2026-06-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itemizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_partida', models.CharField(max_length=30, verbose_name='Código de partida')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('unidad_medida', models.CharField(max_length=20, verbose_name='Unidad de medida')),
                ('cant_presupuestada', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad presupuestada')),
                ('cant_ejecutada', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad ejecutada')),
            ],
            options={
                'verbose_name': 'Itemizado',
                'verbose_name_plural': 'Itemizados',
                'ordering': ['codigo_partida'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del proyecto')),
                ('mandante', models.CharField(max_length=150, verbose_name='Mandante')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de término')),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'En planificación'), ('EJECUCION', 'En ejecución'), ('FINALIZADO', 'Finalizado'), ('SUSPENDIDO', 'Suspendido')], default='PLANIFICACION', max_length=15, verbose_name='Estado')),
                ('presupuesto_total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Presupuesto total (CLP)')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
