# Generated by Django 5.0.6 on 2026-06-11 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='jefe_proyecto',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'JEFE_PROYECTO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Jefe de proyecto'),
        ),
        migrations.AddField(
            model_name='itemizado',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemizados', to='proyectos.proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='itemizado',
            unique_together={('proyecto', 'codigo_partida')},
        ),
    ]
