# Generated by Django 5.2.17 on 2026-09-13 04:11

import django.db.models.deletion
import proyectos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0004_alter_proyecto_jefe_proyecto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Tipo de documento"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descripción"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Tipo de documento",
                "verbose_name_plural": "Tipos de documento",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ArchivoProyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, verbose_name="Nombre del documento"
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=proyectos.models.ruta_archivo_proyecto,
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Observaciones"
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de carga"
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="proyectos.proyecto",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archivos_proyecto_subidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archivos",
                        to="proyectos.tipodocumento",
                        verbose_name="Tipo de documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo del proyecto",
                "verbose_name_plural": "Archivos del proyecto",
                "ordering": ["-fecha"],
            },
        ),
    ]
