# Generated by Django 5.2.17 on 2026-09-29 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0005_tipodocumento_archivoproyecto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="archivoproyecto",
            name="bloqueado_desde",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Bloqueado desde"
            ),
        ),
        migrations.AddField(
            model_name="archivoproyecto",
            name="bloqueado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archivos_bloqueados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bloqueado por",
            ),
        ),
        migrations.AddField(
            model_name="archivoproyecto",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="Versión"),
        ),
    ]
