# Generated by Django 5.0.6 on 2026-06-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del material')),
                ('unidad_medida', models.CharField(max_length=20, verbose_name='Unidad de medida')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock actual')),
                ('precio_referencia', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Precio de referencia (CLP)')),
                ('tipo', models.CharField(choices=[('CONSUMIBLE', 'Material consumible'), ('HERRAMIENTA', 'Herramienta')], default='CONSUMIBLE', max_length=12, verbose_name='Tipo')),
                ('codigo_activo', models.CharField(blank=True, max_length=40, verbose_name='Código de activo (herramienta)')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento (consumible)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
    ]
