# Generated by Django 5.2.17 on 2026-09-11 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_bodega_incremento2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientoinventario",
            name="jefe_proyecto",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "estado": True,
                    "pendiente_aprobacion": False,
                    "rol": "JEFE_PROYECTO",
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos_como_jefe",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Jefe de proyecto",
            ),
        ),
        migrations.AlterField(
            model_name="prestamoherramienta",
            name="jefe_proyecto",
            field=models.ForeignKey(
                limit_choices_to={
                    "estado": True,
                    "pendiente_aprobacion": False,
                    "rol": "JEFE_PROYECTO",
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prestamos_recibidos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Jefe de proyecto",
            ),
        ),
    ]
