# Generated by Django 5.2.17 on 2026-09-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_alter_movimientoinventario_jefe_proyecto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("ARIDOS", "Áridos y hormigones"),
                    ("CEMENTOS", "Cementos y morteros"),
                    ("FIERRO", "Fierro y estructuras"),
                    ("ALBANILERIA", "Albañilería"),
                    ("MADERA", "Madera y moldajes"),
                    ("ELECTRICIDAD", "Electricidad"),
                    ("GASFITERIA", "Gasfitería"),
                    ("TERMINACIONES", "Terminaciones"),
                    ("SEGURIDAD", "Seguridad y EPP"),
                    ("HERRAMIENTA_MANUAL", "Herramienta manual"),
                    ("HERRAMIENTA_ELECTRICA", "Herramienta eléctrica"),
                    ("OTROS", "Otros"),
                ],
                db_index=True,
                default="OTROS",
                max_length=25,
                verbose_name="Categoría",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="codigo_interno",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=20,
                verbose_name="Código interno",
            ),
        ),
    ]
