# Generated by Django 5.2.17 on 2026-09-13 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario_nombre",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Usuario (texto)"
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("MOV_INVENTARIO", "Movimiento de inventario"),
                            ("PRESTAMO_HERRAMIENTA", "Préstamo de herramienta"),
                            ("SM_EMITIDA", "Solicitud de material emitida"),
                            ("SM_APROBADA", "Solicitud de material aprobada"),
                            ("SM_RECHAZADA", "Solicitud de material rechazada"),
                            ("OC_EMITIDA", "Orden de compra emitida"),
                            ("OC_APROBADA", "Orden de compra aprobada"),
                            ("OC_ENVIADA", "Orden de compra enviada al proveedor"),
                            ("FACTURA_RECIBIDA", "Factura recibida"),
                            ("FACTURA_BLOQUEADA", "Factura bloqueada por diferencia"),
                            ("FACTURA_DESBLOQUEADA", "Factura desbloqueada"),
                            ("USUARIO_CREADO", "Cuenta de usuario creada"),
                            ("USUARIO_APROBADO", "Cuenta de usuario aprobada"),
                            ("USUARIO_RECHAZADO", "Cuenta de usuario rechazada"),
                            ("USUARIO_MODIFICADO", "Cuenta de usuario modificada"),
                        ],
                        max_length=30,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("INVENTARIO", "Inventario"),
                            ("SOLICITUDES", "Solicitudes"),
                            ("ADQUISICIONES", "Adquisiciones"),
                            ("FACTURACION", "Facturación"),
                            ("Usuarios", "Usuarios"),
                        ],
                        max_length=20,
                        verbose_name="Módulo",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=250, verbose_name="Descripción"),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Referencia"
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_auditoria",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de auditoría",
                "verbose_name_plural": "Bitácora de auditoría",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["accion"], name="auditoria_r_accion_dae68a_idx"
                    ),
                    models.Index(
                        fields=["modulo", "fecha"], name="auditoria_r_modulo_8eb5ea_idx"
                    ),
                ],
            },
        ),
    ]
