# Generated by Django 5.2.17 on 2026-09-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("MOV_INVENTARIO", "Movimiento de inventario"),
                    ("PRESTAMO_HERRAMIENTA", "Préstamo de herramienta"),
                    ("SM_EMITIDA", "Solicitud de material emitida"),
                    ("SM_APROBADA", "Solicitud de material aprobada"),
                    ("SM_RECHAZADA", "Solicitud de material rechazada"),
                    ("OC_EMITIDA", "Orden de compra emitida"),
                    ("OC_APROBADA", "Orden de compra aprobada"),
                    ("OC_ENVIADA", "Orden de compra enviada al proveedor"),
                    ("FACTURA_RECIBIDA", "Factura recibida"),
                    ("FACTURA_BLOQUEADA", "Factura bloqueada por diferencia"),
                    ("FACTURA_DESBLOQUEADA", "Factura desbloqueada"),
                    ("USUARIO_CREADO", "Cuenta de usuario creada"),
                    ("USUARIO_APROBADO", "Cuenta de usuario aprobada"),
                    ("USUARIO_RECHAZADO", "Cuenta de usuario rechazada"),
                    ("USUARIO_MODIFICADO", "Cuenta de usuario modificada"),
                    ("PARAMETROS_MODIFICADOS", "Parámetros del sistema modificados"),
                ],
                max_length=30,
                verbose_name="Acción",
            ),
        ),
        migrations.AlterField(
            model_name="registroauditoria",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("INVENTARIO", "Inventario"),
                    ("SOLICITUDES", "Solicitudes"),
                    ("ADQUISICIONES", "Adquisiciones"),
                    ("FACTURACION", "Facturación"),
                    ("Usuarios", "Usuarios"),
                    ("CONFIGURACION", "Configuración"),
                ],
                max_length=20,
                verbose_name="Módulo",
            ),
        ),
    ]
