# Generated by Django 5.2.17 on 2026-10-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0002_alter_registroauditoria_accion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("MOV_INVENTARIO", "Movimiento de inventario"),
                    ("PRESTAMO_HERRAMIENTA", "Préstamo de herramienta"),
                    ("SM_EMITIDA", "Solicitud de material emitida"),
                    ("SM_APROBADA", "Solicitud de material aprobada"),
                    ("SM_RECHAZADA", "Solicitud de material rechazada"),
                    ("OC_EMITIDA", "Orden de compra emitida"),
                    ("OC_APROBADA", "Orden de compra aprobada"),
                    ("OC_ENVIADA", "Orden de compra enviada al proveedor"),
                    ("FACTURA_RECIBIDA", "Factura recibida"),
                    ("FACTURA_BLOQUEADA", "Factura bloqueada por diferencia"),
                    ("FACTURA_DESBLOQUEADA", "Factura desbloqueada"),
                    ("USUARIO_CREADO", "Cuenta de usuario creada"),
                    ("USUARIO_APROBADO", "Cuenta de usuario aprobada"),
                    ("USUARIO_RECHAZADO", "Cuenta de usuario rechazada"),
                    ("USUARIO_MODIFICADO", "Cuenta de usuario modificada"),
                    ("USUARIO_ELIMINADO", "Cuenta de usuario eliminada"),
                    ("CAMBIO_PERFIL_PEDIDO", "Cambio de datos solicitado"),
                    ("CAMBIO_PERFIL_RESUELTO", "Cambio de datos resuelto"),
                    ("PARAMETROS_MODIFICADOS", "Parámetros del sistema modificados"),
                ],
                max_length=30,
                verbose_name="Acción",
            ),
        ),
    ]
