# Generated by Django 5.0.6 on 2026-06-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pendiente_aprobacion',
            field=models.BooleanField(default=False, verbose_name='Pendiente de aprobación'),
        ),
    ]
