# Generated by Django 5.2.17 on 2026-09-29 01:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_usuario_rol_contabilidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametrosSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tolerancia_factura_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        help_text="Diferencia máxima aceptada entre el monto de la factura y el total de la orden de compra antes de bloquearla.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Tolerancia de facturación (%)",
                    ),
                ),
                (
                    "stock_minimo_defecto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valor que toma el stock mínimo de un material nuevo cuando no se indica otro. Alimenta la alerta de materiales críticos.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Stock mínimo por defecto",
                    ),
                ),
                (
                    "umbral_archivo_mb",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Sobre este tamaño el sistema advierte antes de completar la carga.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name="Umbral de tamaño de archivo (MB)",
                    ),
                ),
                (
                    "actualizado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parametros_actualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parámetros del sistema",
                "verbose_name_plural": "Parámetros del sistema",
            },
        ),
    ]
