# Generated by Django 5.2.17 on 2026-10-02 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_parametrossistema"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(
                blank=True, upload_to="perfiles/", verbose_name="Foto de perfil"
            ),
        ),
        migrations.CreateModel(
            name="SolicitudCambioPerfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campo",
                    models.CharField(
                        choices=[
                            ("email", "Correo electrónico"),
                            ("username", "Nombre de usuario"),
                            ("rol", "Rol"),
                        ],
                        max_length=20,
                        verbose_name="Dato a cambiar",
                    ),
                ),
                (
                    "valor_actual",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Valor actual"
                    ),
                ),
                (
                    "valor_solicitado",
                    models.CharField(max_length=150, verbose_name="Valor solicitado"),
                ),
                ("motivo", models.TextField(blank=True, verbose_name="Motivo")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "creada",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de solicitud"
                    ),
                ),
                (
                    "resuelta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de resolución"
                    ),
                ),
                (
                    "comentario",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Comentario del administrador",
                    ),
                ),
                (
                    "resuelta_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cambios_resueltos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resuelta por",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cambios_solicitados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de cambio de datos",
                "verbose_name_plural": "Solicitudes de cambio de datos",
                "ordering": ["-creada"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("estado", "PENDIENTE")),
                        fields=("usuario", "campo"),
                        name="una_solicitud_pendiente_por_campo",
                    )
                ],
            },
        ),
    ]
