# Generated by Django 5.0.6 on 2026-06-11 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Correlativo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Solicitud de material',
                'verbose_name_plural': 'Solicitudes de material',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad solicitada')),
                ('unidad_medida', models.CharField(max_length=20, verbose_name='Unidad de medida')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_detalle', to='inventario.material')),
            ],
            options={
                'verbose_name': 'Detalle de solicitud',
                'verbose_name_plural': 'Detalles de solicitud',
            },
        ),
    ]
