# Generated by Django 5.0.6 on 2026-06-11 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0002_initial'),
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmaterial',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_emitidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='solicituddetalle',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='solicitudes.solicitudmaterial'),
        ),
        migrations.AlterUniqueTogether(
            name='solicituddetalle',
            unique_together={('solicitud', 'material')},
        ),
    ]
