# Generated by Django 5.2.17 on 2026-09-11 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0004_proveedormaterial_material"),
        ("solicitudes", "0003_incremento2_justificacion_adjuntos"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicituddetalle",
            name="detalle",
            field=models.CharField(
                blank=True,
                help_text="Opcional: para qué es, dónde va, alguna precisión para el proveedor.",
                max_length=200,
                verbose_name="Detalle",
            ),
        ),
        migrations.AddField(
            model_name="solicituddetalle",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lineas_solicitud",
                to="proveedores.proveedor",
                verbose_name="Proveedor sugerido",
            ),
        ),
        migrations.AddField(
            model_name="solicituddetalle",
            name="proveedor_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lineas_solicitud",
                to="proveedores.proveedormaterial",
                verbose_name="Ítem del catálogo del proveedor",
            ),
        ),
        migrations.AddField(
            model_name="solicituddetalle",
            name="valor_unitario",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Valor unitario estimado (CLP)",
            ),
        ),
        migrations.AlterField(
            model_name="solicituddetalle",
            name="unidad_medida",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Unidad de medida"
            ),
        ),
    ]
