# Generated by Django 5.2.17 on 2026-09-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "solicitudes",
            "0004_solicituddetalle_detalle_solicituddetalle_proveedor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudmaterial",
            name="motivo_rechazo",
            field=models.TextField(blank=True, verbose_name="Motivo del rechazo"),
        ),
    ]
