# Generated by Django 5.0.6 on 2026-06-11 01:45

import usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre / Razón social')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[usuarios.validators.validar_rut], verbose_name='RUT')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('condicion_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('30_DIAS', '30 días'), ('60_DIAS', '60 días'), ('90_DIAS', '90 días')], default='CONTADO', max_length=10, verbose_name='Condición de pago')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
