# Generated by Django 5.2.17 on 2026-09-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0002_proveedormaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedormaterial",
            name="condicion_pago",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONTADO", "Contado"),
                    ("30_DIAS", "30 días"),
                    ("60_DIAS", "60 días"),
                    ("90_DIAS", "90 días"),
                ],
                help_text="Si se deja vacía, se usa la condición por defecto del proveedor.",
                max_length=10,
                verbose_name="Condición de pago",
            ),
        ),
        migrations.AddField(
            model_name="proveedormaterial",
            name="precio",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="Precio unitario (CLP)",
            ),
        ),
    ]
