# Generated by Django 5.2.17 on 2026-09-11 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_alter_movimientoinventario_jefe_proyecto_and_more"),
        ("proveedores", "0003_proveedormaterial_condicion_pago_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedormaterial",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ofertas",
                to="inventario.material",
                verbose_name="Material del catálogo",
            ),
        ),
    ]
